name: fxvtRequester
description: a people api
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  postgres: ^2.4.5
  fxvt:
    git:
      url: ssh://git@git.fatos.biz:30022/source/argos/component/fxvt.git
      ref: fxvt_0.9.4.5
  http: ^0.13.4
  latlong2: ^0.8.1
  string_validator: ^0.3.0
  mailer: ^5.1.1
  crypto: ^3.0.2
  yaml: ^3.1.1
  async_task: ^1.0.18
  convert: ^3.0.2
  shelf_cors_headers: ^0.1.3


dev_dependencies:
  build_runner: ^2.1.11
  build_test: ^2.1.5
  build_web_compilers: ^3.2.3
  collection: ^1.16.0
